# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kana Shimizu
email: shimizu.kana(a)waseda.jp
description: Kana Shimizu's personal page
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://iskana.github.io" # the base hostname & protocol for your site
#twitter_username: hemang_kumar
github_username:  iskana
paginate: 5
#theme-dark: false #Set to true to change to dark website theme
theme-dark: false

plugins: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
